# On ajoute explicitement le préfixe "jdbc:" devant la variable de Render
spring.datasource.url=jdbc:${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}

# Optionnel : désactiver l'avertissement sur le dialecte vu dans vos logs
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect 
spring.jpa.hibernate.ddl-auto=update